### PR TITLE
fix: taxonomy validation for modules

### LINKED ISSUE #1064: Module validation vs. sample taxonomy does not succeed
Steps to reproduce:
1. run 'make pre-test'
2. run manager locally as described in manager/README.md
3. kubectl apply -f manager/testdata/e2e/module-read.yaml -n fybrik-system

Result:
`ERR controllers/app/fybrikmodule_controller.go:74 > Fybrik module validation failed  error="FybrikModule.app.fybrik.io \"read-module-test-e2e\" is invalid: [spec.capabilities.0.actions.0: Invalid value: map[string]interface {}{\"name\":\"RedactAction\"}: Must validate one and only one schema (oneOf), spec.capabilities.0.actions.0: Invalid value: map[string]interface {}{\"name\":\"RedactAction\"}: RedactAction is required, spec.capabilities.0.actions.1: Invalid value: map[string]interface {}{\"name\":\"RemoveAction\"}: Must validate one and only one schema (oneOf), spec.capabilities.0.actions.1: Invalid value: map[string]interface {}{\"name\":\"RemoveAction\"}: RemoveAction is required]" Controller=FybrikModule module=fybrik-system/read-module-test-e2e`

### PR DESCRIPTION
**Pull request by roee88**
Action in module now only declares the unique name of the action.

Closes #1064

### CODE REVIEW

File: manager/apis/app/v1alpha1/fybrikmodule_types.go [hunk 1]
```diff
@@ -99,13 +99,17 @@ type ModuleCapability struct {
...
-	Actions []taxonomy.Action `json:"actions,omitempty"`
+	Actions []ModuleSupportedAction `json:"actions,omitempty"`
 
 	// Plugins enable the module to add libraries to perform actions rather than implementing them by itself
 	// +optional
 	Plugins []Plugin `json:"plugins,omitempty"`
 }
 
+type ModuleSupportedAction struct {
+	Name taxonomy.ActionName `json:"name"`
```
Comment (revit13) [inline manager/apis/app/v1alpha1/fybrikmodule_types.go:110]: Maybe add required

**Review by revit13 — APPROVED** [review]
